### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by Sanatus** [Timardo/LT-3D-Importer#1]
The glass joint is found to be missing or disconnected by importing software
![D5_图片_20220417_192652](https://user-images.githubusercontent.com/88201230/163809185-687d469a-9389-4263-ab1e-43a2c60ce919.png)
![D5_图片_20220417_192116](https://user-images.githubusercontent.com/88201230/163809193-bd96b32f-4e97-4e1c-a310-c4b6befc3a53.png)

**Comment by Timardo** [comment]
Since you didn't specify if this is a problem in Minecraft after importing or in a 3D software after exporting, my guess is the latter.

This is a known problem which is caused by the fact, that LittleTiles cannot span through multiple blocks, thus creating separated "tiles" for each block even though it's the same material. 3D exporter then creates faces between these separated tiles and cause this problem. This issue applies to all translucent materials like glass, leaves and others.

The only temporary fix that comes into my mind is shrinking the whole structure into a grid size that it can fit in (as in one single block) and then export it. This will, however, mess the textures and UV map. I will get to fixing this bug as well as continue my work on this mod and exporting feature when I'd have more free time.
